[program:record_lessons_bot]
directory=/root/Record_Lessons_bot
command=/root/Record_Lessons_bot/venv/bin/python main.py
user=root

autostart=true
autorestart=true
startsecs=10
startretries=5

; asyncio toza yopilishi uchun SIGINT
stopsignal=INT
stopwaitsecs=15
stopasgroup=true
killasgroup=true

environment=PYTHONUNBUFFERED="1"

stdout_logfile=/var/log/record_lessons_bot.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/record_lessons_bot.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
